
package com.rohit.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.2
 * Tue Dec 09 10:48:49 IST 2014
 * Generated source version: 3.0.2
 */

@XmlRootElement(name = "getProductCategories", namespace = "http://rohit.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductCategories", namespace = "http://rohit.com/")

public class GetProductCategories {


}

