
package com.rohit.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.2
 * Tue Dec 09 10:48:49 IST 2014
 * Generated source version: 3.0.2
 */

@XmlRootElement(name = "getProductCategoriesResponse", namespace = "http://rohit.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductCategoriesResponse", namespace = "http://rohit.com/")

public class GetProductCategoriesResponse {

    @XmlElement(name = "return")
    private java.util.List<java.lang.String> _return;

    public java.util.List<java.lang.String> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<java.lang.String> new_return)  {
        this._return = new_return;
    }

}

